name: Update NCAA Stats

# This section tells GitHub WHEN to run the script
on:
  schedule:
    - cron: '15 17-23,00-06 * * *' # Runs at 15 minutes past the hour, at 17:00 through 23:00 and 00:00 through 06:59


  workflow_dispatch: # Allows you to trigger it manually by clicking a button

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# This section tells GitHub WHAT to do
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run Python Script
        env:
          API_KEY: ${{ secrets.API_KEY }} # Pulls your hidden API key
        run: python ncaa_tournament_player_stats.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add NCAA_Tournament_2026_Player_Stats.csv
          git commit -m "Auto-update tournament stats" || echo "No changes to commit"
          git push
